// Multi-language invoice labels
// These translate the invoice OUTPUT — not the form UI

export interface InvoiceLabels {
  invoice: string;
  billTo: string;
  from: string;
  invoiceDate: string;
  dueDate: string;
  description: string;
  quantity: string;
  rate: string;
  amount: string;
  subtotal: string;
  tax: string;
  discount: string;
  shipping: string;
  total: string;
  paymentInformation: string;
  termsAndConditions: string;
  notes: string;
  authorizedSignature: string;
  taxId: string;
  poNumber: string;
}

export interface LanguageOption {
  code: string;
  name: string;        // English name
  nativeName: string;  // Name in its own script
}

export const LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "es", name: "Spanish", nativeName: "Espa\u00f1ol" },
  { code: "fr", name: "French", nativeName: "Fran\u00e7ais" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "pt", name: "Portuguese", nativeName: "Portugu\u00eas" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "hi", name: "Hindi", nativeName: "\u0939\u093f\u0902\u0926\u0940" },
  { code: "ar", name: "Arabic", nativeName: "\u0627\u0644\u0639\u0631\u0628\u064a\u0629" },
  { code: "zh", name: "Chinese", nativeName: "\u4e2d\u6587" },
  { code: "ja", name: "Japanese", nativeName: "\u65e5\u672c\u8a9e" },
  { code: "ko", name: "Korean", nativeName: "\ud55c\uad6d\uc5b4" },
  { code: "tr", name: "Turkish", nativeName: "T\u00fcrk\u00e7e" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "ru", name: "Russian", nativeName: "\u0420\u0443\u0441\u0441\u043a\u0438\u0439" },
  { code: "th", name: "Thai", nativeName: "\u0e44\u0e17\u0e22" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "vi", name: "Vietnamese", nativeName: "Ti\u1ebfng Vi\u1ec7t" },
  { code: "bn", name: "Bengali", nativeName: "\u09ac\u09be\u0982\u09b2\u09be" },
  { code: "ur", name: "Urdu", nativeName: "\u0627\u0631\u062f\u0648" },
];

// jsPDF only supports basic Latin characters — non-Latin scripts fall back to English labels on PDF
// but the preview renders correctly since it's HTML

const TRANSLATIONS: Record<string, InvoiceLabels> = {
  en: {
    invoice: "INVOICE",
    billTo: "Bill To",
    from: "From",
    invoiceDate: "Invoice Date",
    dueDate: "Due Date",
    description: "Description",
    quantity: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    paymentInformation: "Payment Information",
    termsAndConditions: "Terms & Conditions",
    notes: "Notes",
    authorizedSignature: "Authorized Signature",
    taxId: "Tax ID",
    poNumber: "PO",
  },
  es: {
    invoice: "FACTURA",
    billTo: "Facturar A",
    from: "De",
    invoiceDate: "Fecha de Factura",
    dueDate: "Fecha de Vencimiento",
    description: "Descripcion",
    quantity: "Cant.",
    rate: "Precio",
    amount: "Importe",
    subtotal: "Subtotal",
    tax: "Impuesto",
    discount: "Descuento",
    shipping: "Envio",
    total: "Total",
    paymentInformation: "Informacion de Pago",
    termsAndConditions: "Terminos y Condiciones",
    notes: "Notas",
    authorizedSignature: "Firma Autorizada",
    taxId: "NIF/CIF",
    poNumber: "OC",
  },
  fr: {
    invoice: "FACTURE",
    billTo: "Facturer A",
    from: "De",
    invoiceDate: "Date de Facture",
    dueDate: "Date d'Echeance",
    description: "Description",
    quantity: "Qte",
    rate: "Prix",
    amount: "Montant",
    subtotal: "Sous-total",
    tax: "Taxe",
    discount: "Remise",
    shipping: "Livraison",
    total: "Total",
    paymentInformation: "Informations de Paiement",
    termsAndConditions: "Conditions Generales",
    notes: "Notes",
    authorizedSignature: "Signature Autorisee",
    taxId: "N. TVA",
    poNumber: "BC",
  },
  de: {
    invoice: "RECHNUNG",
    billTo: "Rechnungsempfanger",
    from: "Von",
    invoiceDate: "Rechnungsdatum",
    dueDate: "Falligkeitsdatum",
    description: "Beschreibung",
    quantity: "Menge",
    rate: "Preis",
    amount: "Betrag",
    subtotal: "Zwischensumme",
    tax: "Steuer",
    discount: "Rabatt",
    shipping: "Versand",
    total: "Gesamt",
    paymentInformation: "Zahlungsinformationen",
    termsAndConditions: "Allgemeine Geschaftsbedingungen",
    notes: "Anmerkungen",
    authorizedSignature: "Unterschrift",
    taxId: "USt-IdNr.",
    poNumber: "Bestellnr.",
  },
  pt: {
    invoice: "FATURA",
    billTo: "Cobrar De",
    from: "De",
    invoiceDate: "Data da Fatura",
    dueDate: "Data de Vencimento",
    description: "Descricao",
    quantity: "Qtd.",
    rate: "Preco",
    amount: "Valor",
    subtotal: "Subtotal",
    tax: "Imposto",
    discount: "Desconto",
    shipping: "Frete",
    total: "Total",
    paymentInformation: "Informacoes de Pagamento",
    termsAndConditions: "Termos e Condicoes",
    notes: "Observacoes",
    authorizedSignature: "Assinatura Autorizada",
    taxId: "NIF/CNPJ",
    poNumber: "OC",
  },
  it: {
    invoice: "FATTURA",
    billTo: "Fatturare A",
    from: "Da",
    invoiceDate: "Data Fattura",
    dueDate: "Data Scadenza",
    description: "Descrizione",
    quantity: "Qta",
    rate: "Prezzo",
    amount: "Importo",
    subtotal: "Subtotale",
    tax: "IVA",
    discount: "Sconto",
    shipping: "Spedizione",
    total: "Totale",
    paymentInformation: "Dati di Pagamento",
    termsAndConditions: "Termini e Condizioni",
    notes: "Note",
    authorizedSignature: "Firma Autorizzata",
    taxId: "P.IVA",
    poNumber: "OA",
  },
  nl: {
    invoice: "FACTUUR",
    billTo: "Factureren Aan",
    from: "Van",
    invoiceDate: "Factuurdatum",
    dueDate: "Vervaldatum",
    description: "Omschrijving",
    quantity: "Aantal",
    rate: "Prijs",
    amount: "Bedrag",
    subtotal: "Subtotaal",
    tax: "BTW",
    discount: "Korting",
    shipping: "Verzending",
    total: "Totaal",
    paymentInformation: "Betalingsgegevens",
    termsAndConditions: "Algemene Voorwaarden",
    notes: "Opmerkingen",
    authorizedSignature: "Bevoegde Handtekening",
    taxId: "BTW-nr.",
    poNumber: "PO",
  },
  hi: {
    invoice: "INVOICE",  // jsPDF can't render Devanagari — keep English for PDF
    billTo: "Bill To",
    from: "From",
    invoiceDate: "Invoice Date",
    dueDate: "Due Date",
    description: "Description",
    quantity: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "GST",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    paymentInformation: "Payment Information",
    termsAndConditions: "Terms & Conditions",
    notes: "Notes",
    authorizedSignature: "Authorized Signature",
    taxId: "GSTIN",
    poNumber: "PO",
  },
  ar: {
    invoice: "INVOICE",  // jsPDF can't render Arabic — keep English for PDF
    billTo: "Bill To",
    from: "From",
    invoiceDate: "Invoice Date",
    dueDate: "Due Date",
    description: "Description",
    quantity: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "VAT",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    paymentInformation: "Payment Information",
    termsAndConditions: "Terms & Conditions",
    notes: "Notes",
    authorizedSignature: "Authorized Signature",
    taxId: "TRN",
    poNumber: "PO",
  },
  zh: {
    invoice: "INVOICE",  // jsPDF can't render CJK — keep English for PDF
    billTo: "Bill To",
    from: "From",
    invoiceDate: "Invoice Date",
    dueDate: "Due Date",
    description: "Description",
    quantity: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    paymentInformation: "Payment Information",
    termsAndConditions: "Terms & Conditions",
    notes: "Notes",
    authorizedSignature: "Authorized Signature",
    taxId: "Tax ID",
    poNumber: "PO",
  },
  ja: {
    invoice: "INVOICE",
    billTo: "Bill To",
    from: "From",
    invoiceDate: "Invoice Date",
    dueDate: "Due Date",
    description: "Description",
    quantity: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    paymentInformation: "Payment Information",
    termsAndConditions: "Terms & Conditions",
    notes: "Notes",
    authorizedSignature: "Authorized Signature",
    taxId: "Tax ID",
    poNumber: "PO",
  },
  ko: {
    invoice: "INVOICE",
    billTo: "Bill To",
    from: "From",
    invoiceDate: "Invoice Date",
    dueDate: "Due Date",
    description: "Description",
    quantity: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "VAT",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    paymentInformation: "Payment Information",
    termsAndConditions: "Terms & Conditions",
    notes: "Notes",
    authorizedSignature: "Authorized Signature",
    taxId: "Business Reg. No.",
    poNumber: "PO",
  },
  tr: {
    invoice: "FATURA",
    billTo: "Fatura Adresi",
    from: "Gonderen",
    invoiceDate: "Fatura Tarihi",
    dueDate: "Vade Tarihi",
    description: "Aciklama",
    quantity: "Adet",
    rate: "Birim Fiyat",
    amount: "Tutar",
    subtotal: "Ara Toplam",
    tax: "KDV",
    discount: "Indirim",
    shipping: "Kargo",
    total: "Toplam",
    paymentInformation: "Odeme Bilgileri",
    termsAndConditions: "Sartlar ve Kosullar",
    notes: "Notlar",
    authorizedSignature: "Yetkili Imza",
    taxId: "VKN/TCKN",
    poNumber: "Siparis No.",
  },
  pl: {
    invoice: "FAKTURA",
    billTo: "Nabywca",
    from: "Sprzedawca",
    invoiceDate: "Data Wystawienia",
    dueDate: "Termin Platnosci",
    description: "Opis",
    quantity: "Ilosc",
    rate: "Cena",
    amount: "Wartosc",
    subtotal: "Suma Czesciowa",
    tax: "VAT",
    discount: "Rabat",
    shipping: "Wysylka",
    total: "Razem",
    paymentInformation: "Dane do Platnosci",
    termsAndConditions: "Warunki",
    notes: "Uwagi",
    authorizedSignature: "Podpis",
    taxId: "NIP",
    poNumber: "Zamowienie",
  },
  sv: {
    invoice: "FAKTURA",
    billTo: "Faktureras Till",
    from: "Fran",
    invoiceDate: "Fakturadatum",
    dueDate: "Forfallodatum",
    description: "Beskrivning",
    quantity: "Antal",
    rate: "Pris",
    amount: "Belopp",
    subtotal: "Delsumma",
    tax: "Moms",
    discount: "Rabatt",
    shipping: "Frakt",
    total: "Totalt",
    paymentInformation: "Betalningsinformation",
    termsAndConditions: "Villkor",
    notes: "Anteckningar",
    authorizedSignature: "Behrig Underskrift",
    taxId: "Momsreg.nr.",
    poNumber: "Bestallningsnr.",
  },
  da: {
    invoice: "FAKTURA",
    billTo: "Faktureres Til",
    from: "Fra",
    invoiceDate: "Fakturadato",
    dueDate: "Forfaldsdato",
    description: "Beskrivelse",
    quantity: "Antal",
    rate: "Pris",
    amount: "Belob",
    subtotal: "Subtotal",
    tax: "Moms",
    discount: "Rabat",
    shipping: "Fragt",
    total: "Total",
    paymentInformation: "Betalingsoplysninger",
    termsAndConditions: "Betingelser",
    notes: "Noter",
    authorizedSignature: "Autoriseret Underskrift",
    taxId: "CVR-nr.",
    poNumber: "Ordrenr.",
  },
  no: {
    invoice: "FAKTURA",
    billTo: "Faktureres Til",
    from: "Fra",
    invoiceDate: "Fakturadato",
    dueDate: "Forfallsdato",
    description: "Beskrivelse",
    quantity: "Antall",
    rate: "Pris",
    amount: "Belop",
    subtotal: "Delsum",
    tax: "MVA",
    discount: "Rabatt",
    shipping: "Frakt",
    total: "Totalt",
    paymentInformation: "Betalingsinformasjon",
    termsAndConditions: "Vilkar",
    notes: "Merknader",
    authorizedSignature: "Autorisert Signatur",
    taxId: "Org.nr.",
    poNumber: "Bestillingsnr.",
  },
  ru: {
    invoice: "INVOICE",  // Cyrillic not supported in jsPDF default fonts
    billTo: "Bill To",
    from: "From",
    invoiceDate: "Invoice Date",
    dueDate: "Due Date",
    description: "Description",
    quantity: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "NDS",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    paymentInformation: "Payment Information",
    termsAndConditions: "Terms & Conditions",
    notes: "Notes",
    authorizedSignature: "Authorized Signature",
    taxId: "INN",
    poNumber: "PO",
  },
  th: {
    invoice: "INVOICE",
    billTo: "Bill To",
    from: "From",
    invoiceDate: "Invoice Date",
    dueDate: "Due Date",
    description: "Description",
    quantity: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "VAT",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    paymentInformation: "Payment Information",
    termsAndConditions: "Terms & Conditions",
    notes: "Notes",
    authorizedSignature: "Authorized Signature",
    taxId: "Tax ID",
    poNumber: "PO",
  },
  id: {
    invoice: "FAKTUR",
    billTo: "Ditagih Kepada",
    from: "Dari",
    invoiceDate: "Tanggal Faktur",
    dueDate: "Tanggal Jatuh Tempo",
    description: "Deskripsi",
    quantity: "Jml",
    rate: "Harga",
    amount: "Jumlah",
    subtotal: "Subtotal",
    tax: "PPN",
    discount: "Diskon",
    shipping: "Pengiriman",
    total: "Total",
    paymentInformation: "Informasi Pembayaran",
    termsAndConditions: "Syarat dan Ketentuan",
    notes: "Catatan",
    authorizedSignature: "Tanda Tangan",
    taxId: "NPWP",
    poNumber: "PO",
  },
  ms: {
    invoice: "INVOIS",
    billTo: "Bil Kepada",
    from: "Dari",
    invoiceDate: "Tarikh Invois",
    dueDate: "Tarikh Tamat",
    description: "Penerangan",
    quantity: "Kuantiti",
    rate: "Harga",
    amount: "Jumlah",
    subtotal: "Jumlah Kecil",
    tax: "SST",
    discount: "Diskaun",
    shipping: "Penghantaran",
    total: "Jumlah Besar",
    paymentInformation: "Maklumat Pembayaran",
    termsAndConditions: "Terma dan Syarat",
    notes: "Nota",
    authorizedSignature: "Tandatangan Sah",
    taxId: "No. SST",
    poNumber: "PO",
  },
  vi: {
    invoice: "HOA DON",
    billTo: "Gui Den",
    from: "Tu",
    invoiceDate: "Ngay Hoa Don",
    dueDate: "Ngay Den Han",
    description: "Mo Ta",
    quantity: "SL",
    rate: "Don Gia",
    amount: "Thanh Tien",
    subtotal: "Tam Tinh",
    tax: "Thue",
    discount: "Giam Gia",
    shipping: "Van Chuyen",
    total: "Tong Cong",
    paymentInformation: "Thong Tin Thanh Toan",
    termsAndConditions: "Dieu Khoan",
    notes: "Ghi Chu",
    authorizedSignature: "Chu Ky",
    taxId: "MST",
    poNumber: "So DH",
  },
  bn: {
    invoice: "INVOICE",
    billTo: "Bill To",
    from: "From",
    invoiceDate: "Invoice Date",
    dueDate: "Due Date",
    description: "Description",
    quantity: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "VAT",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    paymentInformation: "Payment Information",
    termsAndConditions: "Terms & Conditions",
    notes: "Notes",
    authorizedSignature: "Authorized Signature",
    taxId: "BIN",
    poNumber: "PO",
  },
  ur: {
    invoice: "INVOICE",
    billTo: "Bill To",
    from: "From",
    invoiceDate: "Invoice Date",
    dueDate: "Due Date",
    description: "Description",
    quantity: "Qty",
    rate: "Rate",
    amount: "Amount",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    paymentInformation: "Payment Information",
    termsAndConditions: "Terms & Conditions",
    notes: "Notes",
    authorizedSignature: "Authorized Signature",
    taxId: "NTN",
    poNumber: "PO",
  },
};

export function getLabels(lang: string): InvoiceLabels {
  return TRANSLATIONS[lang] ?? TRANSLATIONS.en;
}

// Tax label presets per currency
const TAX_LABELS: Record<string, string> = {
  USD: "Tax",
  EUR: "VAT",
  GBP: "VAT",
  INR: "GST",
  CAD: "GST/HST",
  AUD: "GST",
  JPY: "Tax",
  CNY: "VAT",
  BRL: "ICMS",
  MXN: "IVA",
  KRW: "VAT",
  SGD: "GST",
  CHF: "VAT",
  SEK: "Moms",
  NOK: "MVA",
  DKK: "Moms",
  ZAR: "VAT",
  AED: "VAT",
  SAR: "VAT",
  NZD: "GST",
  PHP: "VAT",
  THB: "VAT",
  IDR: "PPN",
  MYR: "SST",
  NGN: "VAT",
  PLN: "VAT",
  TRY: "KDV",
  COP: "IVA",
  ARS: "IVA",
  EGP: "VAT",
  PKR: "Sales Tax",
  BDT: "VAT",
};

export function getTaxLabelForCurrency(currency: string): string {
  return TAX_LABELS[currency] ?? "Tax";
}
