export interface CountrySeoData {
  slug: string;
  name: string;
  currency: string;
  taxName: string;
  taxRate: string;
  taxIdName: string;
  legalRequirements: string[];
  paymentMethods: string[];
  faqs: { q: string; a: string }[];
}

export const SEO_COUNTRIES: Record<string, CountrySeoData> = {
  india: {
    slug: "india",
    name: "India",
    currency: "INR",
    taxName: "GST",
    taxRate: "5%, 12%, 18%, or 28% depending on goods/services",
    taxIdName: "GSTIN (15-digit Goods and Services Tax Identification Number)",
    legalRequirements: [
      "GSTIN of the supplier (if registered)",
      "Invoice number (sequential, unique)",
      "Date of issue",
      "Name, address, and GSTIN of the recipient (if registered)",
      "HSN code or SAC code for goods/services",
      "Description, quantity, and unit price",
      "Total taxable value",
      "Rate and amount of CGST, SGST, IGST, and Cess",
      "Place of supply (state name and code)",
      "Signature of authorized person",
    ],
    paymentMethods: [
      "UPI (Google Pay, PhonePe, Paytm)",
      "NEFT / RTGS / IMPS bank transfer",
      "Cheque",
      "Cash (subject to limits)",
      "Digital wallets",
    ],
    faqs: [
      { q: "Is GST mandatory on every invoice in India?", a: "GST is required on invoices issued by registered businesses (turnover above ₹20 lakh for services, ₹40 lakh for goods). Unregistered businesses can issue 'bill of supply' without GST." },
      { q: "What is the difference between CGST, SGST, and IGST?", a: "For intra-state sales, you charge CGST + SGST (split equally). For inter-state sales, you charge IGST (the full GST rate). Our generator handles this automatically based on your state and the customer's state." },
      { q: "Do I need to add HSN/SAC codes on invoices?", a: "Yes, if your turnover exceeds ₹5 crore, you must include 6-digit HSN/SAC codes. Below that, 4-digit codes or no codes are allowed depending on category." },
      { q: "Is e-invoicing mandatory in India?", a: "E-invoicing is mandatory for businesses with turnover above ₹5 crore (as of 2023). Use our generator for non-e-invoice scenarios or as a draft before generating e-invoice via the official portal." },
    ],
  },
  uk: {
    slug: "uk",
    name: "United Kingdom",
    currency: "GBP",
    taxName: "VAT",
    taxRate: "20% standard rate, 5% reduced, 0% zero-rated",
    taxIdName: "VAT Number (9 digits, prefixed with GB)",
    legalRequirements: [
      "Unique invoice number (sequential)",
      "Your business name and address",
      "Your VAT number (if VAT-registered)",
      "Customer's name and address",
      "Invoice date and time of supply (tax point)",
      "Description of goods/services",
      "Quantity and unit price",
      "VAT rate and amount per item",
      "Total amount (excluding VAT, including VAT)",
      "Reference to reverse charge if applicable",
    ],
    paymentMethods: [
      "BACS / Faster Payments bank transfer",
      "Direct Debit",
      "Cheque",
      "PayPal",
      "Stripe / GoCardless",
      "Wise (TransferWise)",
    ],
    faqs: [
      { q: "Do I need to register for VAT in the UK?", a: "VAT registration is mandatory if your taxable turnover exceeds £90,000 in any 12-month period. You can also register voluntarily below this threshold." },
      { q: "What VAT rate should I charge?", a: "Standard rate is 20% for most goods/services. Reduced 5% applies to home energy, child car seats, etc. Zero-rated includes most food, books, and children's clothes. Some services are exempt." },
      { q: "Can I issue an invoice without being VAT-registered?", a: "Yes. If you're not VAT-registered, your invoice should not include VAT. Just don't add a VAT line and don't include a VAT number." },
      { q: "What is reverse charge VAT?", a: "Reverse charge means the customer accounts for VAT instead of the supplier. Common in B2B services across EU borders and in the UK construction industry. Add a reverse charge note to your invoice." },
    ],
  },
  usa: {
    slug: "usa",
    name: "United States",
    currency: "USD",
    taxName: "Sales Tax",
    taxRate: "Varies by state (0% to ~10%)",
    taxIdName: "EIN (Employer Identification Number, 9 digits) or SSN for sole proprietors",
    legalRequirements: [
      "Your business name and address",
      "Customer name and address",
      "Invoice number (sequential, unique)",
      "Invoice date and due date",
      "Description of goods/services",
      "Quantity and unit price",
      "Subtotal, tax, and total",
      "Payment terms",
      "Your EIN or Tax ID (recommended, not always required)",
    ],
    paymentMethods: [
      "ACH / Wire transfer",
      "Check",
      "PayPal / Venmo / Zelle",
      "Stripe / Square",
      "Credit/Debit card",
    ],
    faqs: [
      { q: "Do US freelancers need to charge sales tax?", a: "Most states don't tax services, only physical goods. However, rules vary widely by state. Check your state's Department of Revenue for service taxability." },
      { q: "Do I need an EIN to invoice clients?", a: "No. Sole proprietors can use their SSN. However, an EIN is recommended for privacy and professionalism — it's free from the IRS." },
      { q: "What information must a US invoice include?", a: "There's no federal law mandating invoice format, but standard practice includes business info, client info, invoice number, dates, line items, subtotal, tax (if applicable), and total." },
    ],
  },
  canada: {
    slug: "canada",
    name: "Canada",
    currency: "CAD",
    taxName: "GST/HST/PST",
    taxRate: "5% GST + provincial (or 13-15% HST in HST provinces)",
    taxIdName: "GST/HST Number (9 digits + RT0001 suffix)",
    legalRequirements: [
      "Business name and address",
      "Customer name and address",
      "Invoice number and date",
      "GST/HST number (if registered)",
      "Description of goods/services",
      "Subtotal, GST/HST, PST (if applicable), total",
      "Payment terms",
    ],
    paymentMethods: [
      "Interac e-Transfer",
      "EFT / Wire transfer",
      "Cheque",
      "PayPal",
      "Credit card",
    ],
    faqs: [
      { q: "When do I need to register for GST/HST in Canada?", a: "Registration is mandatory if your gross revenue exceeds $30,000 in any 12-month period. Below that, you're a 'small supplier' and can choose to register voluntarily." },
      { q: "Which provinces use HST vs GST + PST?", a: "HST provinces: ON (13%), NB/NL/NS/PE (15%). GST-only: AB, NT, NU, YT (5%). GST + PST: BC, SK, MB, QC (rates vary)." },
    ],
  },
  australia: {
    slug: "australia",
    name: "Australia",
    currency: "AUD",
    taxName: "GST",
    taxRate: "10% standard rate",
    taxIdName: "ABN (Australian Business Number, 11 digits)",
    legalRequirements: [
      "The words 'Tax Invoice' clearly displayed",
      "Your business name and ABN",
      "Date of issue",
      "Buyer's name (if invoice over $1,000)",
      "Description of goods/services",
      "Quantity and price",
      "GST amount or 'Total price includes GST'",
      "Total amount payable",
    ],
    paymentMethods: [
      "BPAY",
      "Direct deposit / EFT",
      "PayID / Osko",
      "PayPal",
      "Stripe",
      "Credit card",
    ],
    faqs: [
      { q: "Do I need an ABN to invoice in Australia?", a: "Yes — without an ABN, your client must withhold 47% of the payment. Get an ABN free from the ATO before invoicing." },
      { q: "When must I register for GST in Australia?", a: "GST registration is mandatory if your business turnover is $75,000 or more (or $150,000 for non-profits). Below that, registration is optional." },
      { q: "Must I write 'Tax Invoice' on my invoice?", a: "Yes — Australian tax law requires the words 'Tax Invoice' to be prominently displayed on any invoice that includes GST." },
    ],
  },
  uae: {
    slug: "uae",
    name: "United Arab Emirates",
    currency: "AED",
    taxName: "VAT",
    taxRate: "5% standard rate",
    taxIdName: "TRN (Tax Registration Number, 15 digits)",
    legalRequirements: [
      "The words 'Tax Invoice' clearly displayed",
      "Supplier's name, address, and TRN",
      "Recipient's name, address, and TRN (if registered)",
      "Sequential invoice number",
      "Date of issue and date of supply",
      "Description, quantity, unit price",
      "Discounts (if any)",
      "Taxable amount and VAT rate",
      "Total VAT amount in AED",
      "Total amount including VAT",
    ],
    paymentMethods: [
      "Bank transfer (local & international)",
      "Cheque",
      "Credit card",
      "Cash (with limits for VAT compliance)",
      "Digital wallets",
    ],
    faqs: [
      { q: "Is VAT mandatory for businesses in UAE?", a: "VAT registration is mandatory if your annual taxable supplies exceed AED 375,000. Voluntary registration is allowed above AED 187,500." },
      { q: "Do I need to issue invoices in Arabic?", a: "Tax invoices can be issued in English or Arabic. However, the Federal Tax Authority may request Arabic translation for audits." },
      { q: "What is the standard VAT rate in UAE?", a: "5% — one of the lowest VAT rates globally. Some categories (basic food, healthcare, education) are zero-rated." },
    ],
  },
  singapore: {
    slug: "singapore",
    name: "Singapore",
    currency: "SGD",
    taxName: "GST",
    taxRate: "9% standard rate",
    taxIdName: "GST Registration Number (UEN-based)",
    legalRequirements: [
      "Words 'Tax Invoice' (if GST-registered)",
      "Supplier's name and address",
      "GST registration number",
      "Customer's name and address",
      "Invoice number and date",
      "Description and quantity",
      "Total before GST",
      "GST amount and rate",
      "Total inclusive of GST",
    ],
    paymentMethods: [
      "PayNow / FAST",
      "GIRO",
      "Bank transfer",
      "Credit card",
      "PayPal",
    ],
    faqs: [
      { q: "When must I register for GST in Singapore?", a: "Registration is mandatory if your taxable turnover exceeds S$1 million in the past 12 months or expected in the next 12 months." },
    ],
  },
  germany: {
    slug: "germany",
    name: "Germany",
    currency: "EUR",
    taxName: "USt (VAT)",
    taxRate: "19% standard, 7% reduced",
    taxIdName: "Steuernummer or USt-IdNr (VAT Identification Number)",
    legalRequirements: [
      "Full name and address of supplier and customer",
      "Tax number (Steuernummer) or USt-IdNr",
      "Invoice date",
      "Sequential invoice number",
      "Quantity and description",
      "Date of supply",
      "Net amount, VAT rate, VAT amount, gross total",
      "Reference to tax exemption if applicable",
    ],
    paymentMethods: [
      "SEPA bank transfer",
      "PayPal",
      "Klarna",
      "Stripe",
      "Direct debit (Lastschrift)",
    ],
    faqs: [
      { q: "Is VAT registration mandatory in Germany?", a: "Small businesses with turnover under €22,000/year qualify for the Kleinunternehmerregelung (small business rule) and don't charge VAT. Above this, VAT registration is mandatory." },
    ],
  },
  brazil: {
    slug: "brazil",
    name: "Brazil",
    currency: "BRL",
    taxName: "Various (ICMS, ISS, PIS, COFINS)",
    taxRate: "Varies by state and service type",
    taxIdName: "CNPJ (14 digits)",
    legalRequirements: [
      "CNPJ of supplier and customer",
      "Nota Fiscal Eletrônica (NF-e) for goods",
      "Nota Fiscal de Serviço (NFS-e) for services",
      "Itemized goods/services with codes",
      "Tax breakdown by type",
      "Sequential invoice number",
    ],
    paymentMethods: [
      "PIX (instant payment)",
      "Boleto bancário",
      "Bank transfer",
      "Credit card",
    ],
    faqs: [
      { q: "Is electronic invoicing mandatory in Brazil?", a: "Yes — Nota Fiscal Eletrônica (NF-e) is mandatory for goods, and NFS-e for services in most municipalities. Use our generator for drafts and reference; final invoices must be issued via the official municipal/state systems." },
    ],
  },
  "south-africa": {
    slug: "south-africa",
    name: "South Africa",
    currency: "ZAR",
    taxName: "VAT",
    taxRate: "15% standard rate",
    taxIdName: "VAT Number (10 digits, starting with 4)",
    legalRequirements: [
      "Words 'Tax Invoice' on the document",
      "Name, address, and VAT number of supplier",
      "Name and address of recipient",
      "Sequential invoice number",
      "Date of issue",
      "Full description of goods/services",
      "Quantity and price",
      "VAT charged or 'inclusive of VAT'",
      "Total in rand",
    ],
    paymentMethods: [
      "EFT (Electronic Funds Transfer)",
      "PayShap (instant payment)",
      "Credit card",
      "PayPal",
    ],
    faqs: [
      { q: "When is VAT registration required in South Africa?", a: "VAT registration is mandatory if your taxable turnover exceeds R1 million in any 12-month period. Voluntary registration is allowed above R50,000." },
    ],
  },
};

export const SEO_COUNTRY_LIST = Object.values(SEO_COUNTRIES);
