import { TemplateConfig, TemplateId } from "@/types/invoice";

export const TEMPLATES: Record<TemplateId, TemplateConfig> = {
  classic: {
    id: "classic",
    name: "Classic",
    description: "Timeless dark navy design with serif fonts",
    primaryColor: "#1a1a2e",
    accentColor: "#16213e",
    headerBg: "#1a1a2e",
    fontStyle: "serif",
  },
  modern: {
    id: "modern",
    name: "Modern",
    description: "Clean blue design with sans-serif fonts",
    primaryColor: "#2563eb",
    accentColor: "#3b82f6",
    headerBg: "#2563eb",
    fontStyle: "sans",
  },
  minimal: {
    id: "minimal",
    name: "Minimal",
    description: "Light & airy with subtle grey tones",
    primaryColor: "#374151",
    accentColor: "#6b7280",
    headerBg: "#f9fafb",
    fontStyle: "sans",
  },
  bold: {
    id: "bold",
    name: "Bold",
    description: "Striking red for high-impact invoices",
    primaryColor: "#dc2626",
    accentColor: "#ef4444",
    headerBg: "#dc2626",
    fontStyle: "sans",
  },
  elegant: {
    id: "elegant",
    name: "Elegant",
    description: "Sophisticated teal with serif fonts",
    primaryColor: "#0d9488",
    accentColor: "#14b8a6",
    headerBg: "#0d9488",
    fontStyle: "serif",
  },
  executive: {
    id: "executive",
    name: "Executive",
    description: "Dark mode with gold accents — luxury feel",
    primaryColor: "#d4a843",
    accentColor: "#b8962e",
    headerBg: "#1c1c1e",
    fontStyle: "serif",
  },
  creative: {
    id: "creative",
    name: "Creative",
    description: "Gradient purple-to-pink for studios & agencies",
    primaryColor: "#7c3aed",
    accentColor: "#ec4899",
    headerBg: "#7c3aed",
    fontStyle: "sans",
  },
  pastel: {
    id: "pastel",
    name: "Pastel",
    description: "Soft sage & cream for wellness & lifestyle brands",
    primaryColor: "#6b8f71",
    accentColor: "#a3c4a8",
    headerBg: "#f5f0e8",
    fontStyle: "serif",
  },
  monochrome: {
    id: "monochrome",
    name: "Mono",
    description: "Pure black & white — maximum formality",
    primaryColor: "#000000",
    accentColor: "#404040",
    headerBg: "#ffffff",
    fontStyle: "sans",
  },
  sidebar: {
    id: "sidebar",
    name: "Sidebar",
    description: "Bold left sidebar with branding stripe",
    primaryColor: "#1e3a5f",
    accentColor: "#2563eb",
    headerBg: "#1e3a5f",
    fontStyle: "sans",
  },
};

export const COLOR_PRESETS = [
  { name: "Ocean", primary: "#0369a1", accent: "#0ea5e9" },
  { name: "Forest", primary: "#15803d", accent: "#22c55e" },
  { name: "Sunset", primary: "#ea580c", accent: "#f97316" },
  { name: "Plum", primary: "#7c3aed", accent: "#a78bfa" },
  { name: "Rose", primary: "#be123c", accent: "#f43f5e" },
  { name: "Slate", primary: "#334155", accent: "#64748b" },
  { name: "Amber", primary: "#b45309", accent: "#f59e0b" },
  { name: "Indigo", primary: "#4338ca", accent: "#6366f1" },
  { name: "Cyan", primary: "#0e7490", accent: "#06b6d4" },
  { name: "Fuchsia", primary: "#a21caf", accent: "#d946ef" },
];
