"use client";

import { useState, useEffect, useCallback } from "react";
import { InvoiceData } from "@/types/invoice";

interface SavedTemplate {
  name: string;
  data: InvoiceData;
  savedAt: string;
  recurrence?: string;
  lastGeneratedAt?: string;
}

interface DueTemplate {
  index: number;
  template: SavedTemplate;
  daysOverdue: number;
}

const STORAGE_KEY = "invoicegen_saved_templates";
const DISMISSED_KEY = "invoicegen_dismissed_reminders";

const RECURRENCE_DAYS: Record<string, number> = {
  weekly: 7,
  "bi-weekly": 14,
  monthly: 30,
  quarterly: 90,
  yearly: 365,
};

function getDueTemplates(): DueTemplate[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const templates: SavedTemplate[] = JSON.parse(raw);
    const dismissed: string[] = JSON.parse(localStorage.getItem(DISMISSED_KEY) || "[]");
    const now = new Date();
    const due: DueTemplate[] = [];

    templates.forEach((t, i) => {
      if (!t.recurrence || t.recurrence === "none") return;
      const intervalDays = RECURRENCE_DAYS[t.recurrence];
      if (!intervalDays) return;

      // Use lastGeneratedAt if available, otherwise savedAt
      const lastDate = new Date(t.lastGeneratedAt || t.savedAt);
      const nextDue = new Date(lastDate);
      nextDue.setDate(nextDue.getDate() + intervalDays);

      if (now >= nextDue) {
        const dismissKey = `${t.name}_${nextDue.toISOString().split("T")[0]}`;
        if (dismissed.includes(dismissKey)) return;

        const diffMs = now.getTime() - nextDue.getTime();
        const daysOverdue = Math.floor(diffMs / (1000 * 60 * 60 * 24));
        due.push({ index: i, template: t, daysOverdue });
      }
    });

    return due;
  } catch {
    return [];
  }
}

function requestNotificationPermission() {
  if ("Notification" in window && Notification.permission === "default") {
    Notification.requestPermission();
  }
}

function sendBrowserNotification(title: string, body: string) {
  if ("Notification" in window && Notification.permission === "granted") {
    new Notification(title, {
      body,
      icon: "/favicon.ico",
      tag: "invoicegen-recurring",
    });
  }
}

interface RecurringReminderProps {
  onLoadTemplate: (index: number) => void;
}

export default function RecurringReminder({ onLoadTemplate }: RecurringReminderProps) {
  const [dueTemplates, setDueTemplates] = useState<DueTemplate[]>([]);
  const [notifRequested, setNotifRequested] = useState(false);

  useEffect(() => {
    const due = getDueTemplates();
    setDueTemplates(due);

    // Send browser notification for due invoices
    if (due.length > 0) {
      requestNotificationPermission();
      // Delay notification slightly so permission prompt resolves first
      setTimeout(() => {
        if (due.length === 1) {
          sendBrowserNotification(
            "Invoice Reminder",
            `Your ${due[0].template.recurrence} invoice "${due[0].template.name}" is due. Tap to create it.`
          );
        } else {
          sendBrowserNotification(
            "Invoice Reminders",
            `You have ${due.length} recurring invoices due. Open InvoiceGen to create them.`
          );
        }
      }, 2000);
    }
  }, []);

  const handleDismiss = useCallback((dt: DueTemplate) => {
    try {
      const dismissed: string[] = JSON.parse(localStorage.getItem(DISMISSED_KEY) || "[]");
      const intervalDays = RECURRENCE_DAYS[dt.template.recurrence || "monthly"] || 30;
      const lastDate = new Date(dt.template.lastGeneratedAt || dt.template.savedAt);
      const nextDue = new Date(lastDate);
      nextDue.setDate(nextDue.getDate() + intervalDays);
      const dismissKey = `${dt.template.name}_${nextDue.toISOString().split("T")[0]}`;
      dismissed.push(dismissKey);
      // Keep only last 50 dismissals to prevent bloat
      localStorage.setItem(DISMISSED_KEY, JSON.stringify(dismissed.slice(-50)));
    } catch {
      // ignore
    }
    setDueTemplates((prev) => prev.filter((t) => t.index !== dt.index));
  }, []);

  const handleCreate = useCallback((dt: DueTemplate) => {
    // Mark as generated by updating lastGeneratedAt
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const templates: SavedTemplate[] = JSON.parse(raw);
        if (templates[dt.index]) {
          templates[dt.index].lastGeneratedAt = new Date().toISOString();
          localStorage.setItem(STORAGE_KEY, JSON.stringify(templates));
        }
      }
    } catch {
      // ignore
    }
    setDueTemplates((prev) => prev.filter((t) => t.index !== dt.index));
    onLoadTemplate(dt.index);
  }, [onLoadTemplate]);

  if (dueTemplates.length === 0) {
    // Show notification opt-in if not yet requested and there are recurring templates
    if (!notifRequested && "Notification" in (typeof window !== "undefined" ? window : {}) && Notification.permission === "default") {
      try {
        const raw = localStorage.getItem(STORAGE_KEY);
        const templates: SavedTemplate[] = raw ? JSON.parse(raw) : [];
        const hasRecurring = templates.some((t) => t.recurrence && t.recurrence !== "none");
        if (hasRecurring) {
          return (
            <div className="bg-blue-50 border border-blue-200 rounded-xl px-4 py-3 flex items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <svg className="w-5 h-5 text-blue-500 shrink-0" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
                </svg>
                <p className="text-xs text-blue-800">Enable notifications to get reminders when recurring invoices are due.</p>
              </div>
              <button
                onClick={() => {
                  requestNotificationPermission();
                  setNotifRequested(true);
                }}
                className="shrink-0 px-3 py-1.5 bg-blue-600 text-white text-xs font-medium rounded-lg hover:bg-blue-700 transition-colors"
              >
                Enable
              </button>
            </div>
          );
        }
      } catch {
        // ignore
      }
    }
    return null;
  }

  return (
    <div className="space-y-3">
      {dueTemplates.map((dt) => (
        <div
          key={dt.index}
          className="bg-gradient-to-r from-purple-50 to-indigo-50 border border-purple-200 rounded-xl px-4 py-3.5 flex items-center gap-4"
        >
          {/* Icon */}
          <div className="w-10 h-10 rounded-xl bg-purple-100 flex items-center justify-center shrink-0">
            <svg className="w-5 h-5 text-purple-600" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182" />
            </svg>
          </div>

          {/* Info */}
          <div className="flex-1 min-w-0">
            <p className="text-sm font-semibold text-gray-900 truncate">
              {dt.template.name}
              <span className="ml-2 text-xs font-medium text-purple-600 capitalize">({dt.template.recurrence})</span>
            </p>
            <p className="text-xs text-gray-500 mt-0.5">
              {dt.daysOverdue === 0
                ? "Due today!"
                : `${dt.daysOverdue} day${dt.daysOverdue !== 1 ? "s" : ""} overdue`}
              {dt.template.data.clientName && ` \u00b7 ${dt.template.data.clientName}`}
            </p>
          </div>

          {/* Actions */}
          <div className="flex gap-2 shrink-0">
            <button
              onClick={() => handleCreate(dt)}
              className="px-3 py-1.5 bg-gradient-to-r from-purple-600 to-indigo-600 text-white text-xs font-semibold rounded-lg shadow-sm hover:shadow-md transition-all"
            >
              Create Now
            </button>
            <button
              onClick={() => handleDismiss(dt)}
              className="px-2 py-1.5 text-gray-400 text-xs hover:text-gray-600 transition-colors"
              title="Dismiss"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      ))}
    </div>
  );
}
